"""add Langauges to posts

Revision ID: f815a599c43f
Revises: 762470d7fa7c
Create Date: 2021-08-06 10:07:34.752018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f815a599c43f'
down_revision = '762470d7fa7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('langauge', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'langauge')
    # ### end Alembic commands ###
